### ISSUE TITLE
Please add PHP 7.3 Support

### ISSUE THREAD

**Issue by beyondmediadev** [magesuite/page-cache-warmer#2]

**Comment by krisdante** [comment]
Hello @beyondmedia 
Do you use this module standalone?

**Comment by beyondmediadev** [comment]
yes

**Comment by krisdante** [comment]
Amazing :). I think that there is actually nothing that prevents this module to work with PHP 7.3 except of constrain. I will take a risk and bump it.

**Comment by sunel** [comment]
But the dep has version issue https://github.com/magesuite/page-cache-warmer-crawl-worker/issues/1

**Comment by diwipl** [comment]
I've added tag there so version constraint should not longer be an issue.
